



import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Message from '../components/Message'
import User from '../components/User'
import {useState, useEffect, useContext} from 'react'
import AppContext from '../AppContext'
import { db } from '../firebase/Firebase'
import { collection, getDoc, doc, query, orderBy, addDoc } from 'firebase/firestore'
import { useCollectionData } from 'react-firebase-hooks/firestore'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPaperPlane, faXmarkCircle, faBars, faHouse } from '@fortawesome/free-solid-svg-icons'

export default function Home() {
	// messages
	const messagesRef = query(collection(db, 'global'), orderBy('timestamp'))
	const messages = useCollectionData(messagesRef)[0]

	const {name, uid, state, signIn} = useContext(AppContext)

	// state
	const [usernav, setUsernav] = useState(false)

	const aichat = async (msg:any) => {
		send(msg)
		const text = msg.replace('@chatgpt', '')
		const response = await fetch('/api/chatgpt?message=' + text)
		const res = await response.text()
		text != '' ?
		addDoc(collection(db, 'global'), {
			user: 'ChatGPT',
			uid: 'chatgpt@firechat',
			message: res,
			reacts: 0,
			timestamp: new Date(),
			replies: ''
		}) : console.log(msg)
	}

	const handleSend = () => {
		const node = (document.getElementById('input-field') as HTMLInputElement)
		const msg = node.value
		if (msg.includes('@chatgpt')) {
			aichat(msg)
		} else {
			send(msg)
		}
		node.value = ''
	}

	const send = (msg:any) => {
		msg != '' ?
		addDoc(collection(db, 'global'), {
			user: name,
			uid: uid,
			message: msg,
			reacts: 0,
			timestamp: new Date(),
			replies: ''
		}) : console.log(msg)
	}

	const check = (event:any) =>{
		event.keyCode == 13 ? handleSend() : null
	}

	useEffect(() => {
		const node = document.getElementById('messages')
		node!.scrollTop = node!.scrollHeight
	}, [messages])

  return (
    <div>
      <Head>
        <title>FireChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<div className={`${styles.gridContainer} h-screen`}>
				<nav className={`MontAlt flex flex-row justify-between items-center p-4 bg-[#000] text-white ${styles.navbar}`}>
					<div >FireChat</div>
					<div className={`md:hidden ${usernav ? 'hidden' : ''}`}>
						<FontAwesomeIcon icon={faBars} onClick={() => setUsernav(true)}/>
					</div>
				</nav>
				<User usernav={usernav} setUsernav={setUsernav}/>
				<div className={`flex flex-col overflow-y-scroll ${styles.messages}`} id="messages">
					{
						messages && messages.map(msg => <Message key={msg.timestamp} message={msg.message} username={msg.user} pos={msg.uid == uid ? 'right' : 'left'}/>)
					}
				</div>
				<div className={`flex justify-around items-center w-full p-2 bg-black ${styles.footer}`}>
					{
						state ? 
							<>
								<input type="text" className="h-10 rounded-full grow p-2 m-4" id="input-field" onKeyDown={(event) => check(event)}/>
								<div className="cursor-pointer" onClick={() => handleSend()}>
									<FontAwesomeIcon icon={faPaperPlane} className="text-white fa-xl mr-4"/>
								</div> 
							</>
							:
							<div className="p-4 rounded-full bg-blue-400 text-white cursor-pointer" onClick={() => signIn()}>Login to send messages</div>
					}
				</div>
			</div>
    </div>
  )
}
