




import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState, useEffect} from 'react'
import { db } from '../firebase/Firebase'
import { collection, getDoc, doc, query } from 'firebase/firestore'
import { useCollectionData } from 'react-firebase-hooks/firestore'

export default function Home() {
	const usersRef = query(collection(db, 'users'))
	const users = useCollectionData(usersRef)[0]
	console.log(users)
  return (
    <div className="h-screen">
      <Head>
        <title>FireChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<div className="flex flex-col h-full">
				<nav className="MontAlt flex flex-row justify-center items-center p-4 bg-[#000] text-white">
					<div >FireChat</div>
				</nav>
				<main className="bg-[rgba(50,50,50,0.5)] h-full">
					<a href="/Global">Global Chat</a>
				</main>
			</div>
    </div>
  )
}
